const defaults = {
	disablePref: false,
	subtitlePref: false,
	filePref: true,
	downloadDirectPref: false,
	autoDownloadPref: false,
	fileSizePref: false,
	fileSizeAmount: "1",
	manifestPref: false,
	copyMethod: "url",
	userCommand: "",
	regexCommandPref: false,
	regexCommand: "",
	regexReplace: "",
	customExtPref: false,
	customExtEntries: [],
	customCtPref: false,
	customCtEntries: [],
	headersPref: true,
	titlePref: true,
	filenamePref: false,
	timestampPref: false,
	fileExtension: "ts",
	streamlinkOutput: "file",
	downloaderPref: false,
	proxyPref: false,
	customCommandPref: false,
	customCommand: "",
	blacklistPref: false,
	blacklistEntries: [],
	cleanupPref: false,
	recentPref: false,
	recentAmount: "5",
	notifDetectPref: true,
	notifPref: false,
	urlStorageRestore: [],
	urlStorage: [],
	tabThis: true
};

export default defaults;
