const defaults = {
	disablePref: false,
	copyMethod: "url",
	headersPref: true,
	titlePref: true,
	filenamePref: false,
	timestampPref: false,
	subtitlePref: false,
	filePref: true,
	manifestPref: false,
	fileExtension: "ts",
	streamlinkOutput: "file",
	downloaderPref: false,
	proxyPref: false,
	customCommandPref: false,
	blacklistPref: false,
	blacklistEntries: [],
	customExtPref: false,
	customExtEntries: [],
	customCtPref: false,
	customCtEntries: [],
	cleanupPref: false,
	notifDetectPref: true,
	notifPref: false,
	urlStorageRestore: [],
	urlStorage: [],
	tabThis: true
};

export default defaults;
